"""
Google Gemini AI Service Module for Braille Display Website

This module integrates with Google Gemini API for:
- Voice-based AI chat assistance
- Image description/transcription
- Text generation
"""

from django.conf import settings
import base64
import json

# Try to import google-genai (new package)
try:
    from google import genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False
    print("Warning: google-genai not installed. Install with: pip install google-genai")


class GeminiService:
    """
    Service class for Google Gemini AI interactions.
    """
    
    def __init__(self):
        self.api_key = settings.GEMINI_API_KEY
        self.api_available = self.api_key and self.api_key != 'YOUR_GEMINI_API_KEY_HERE' and GEMINI_AVAILABLE
        
        if self.api_available:
            self.client = genai.Client(api_key=self.api_key)
            print("✓ Gemini AI configured successfully with google-genai")
        else:
            print("✗ Gemini AI not configured - using placeholder responses")
    
    def chat(self, message, conversation_history=None):
        """
        Send a message to Gemini and get AI response.
        
        Args:
            message (str): User's message/question
            conversation_history (list): Optional conversation history
        
        Returns:
            dict: Response with AI answer
        """
        if not self.api_available:
            return self._get_placeholder_response(message)
        
        try:
            response = self.client.models.generate_content(
                model='gemini-1.5-flash',
                contents=message
            )
            
            return {
                'status': 'success',
                'response': response.text,
                'source': 'gemini'
            }
        except Exception as e:
            print(f"Gemini API error: {e}")
            return {
                'status': 'error',
                'response': f"I'm having trouble connecting right now. Error: {str(e)}",
                'source': 'error'
            }
    
    def describe_image(self, image_path, prompt="Describe this image in detail for a visually impaired person."):
        """
        Generate description of an image using Gemini Vision.
        
        Args:
            image_path (str): Path to the image file
            prompt (str): Custom prompt for image description
        
        Returns:
            dict: Image description
        """
        if not self.api_available:
            return {
                'status': 'success',
                'description': 'This is a placeholder image description. The actual description would be generated by Gemini Vision API.',
                'source': 'placeholder'
            }
        
        try:
            # Read image file
            with open(image_path, 'rb') as f:
                image_data = f.read()
            
            # Create part with image data
            from google.genai import types
            image_part = types.Part.from_bytes(
                data=image_data,
                mime_type='image/jpeg'
            )
            
            # Generate description
            response = self.client.models.generate_content(
                model='gemini-1.5-flash',
                contents=[image_part, prompt]
            )
            
            return {
                'status': 'success',
                'description': response.text,
                'source': 'gemini-vision'
            }
        except Exception as e:
            error_msg = str(e)
            print(f"Gemini Vision error: {error_msg}")
            
            # Provide user-friendly error messages
            if "quota" in error_msg.lower():
                friendly_msg = "API quota exceeded. Please try again later."
            elif "connection" in error_msg.lower() or "network" in error_msg.lower():
                friendly_msg = "Network connection error. Please check your internet connection."
            elif "invalid" in error_msg.lower() and "api" in error_msg.lower():
                friendly_msg = "Invalid API key. Please check your Gemini API configuration."
            else:
                friendly_msg = f"Could not process image: {error_msg}"
            
            return {
                'status': 'error',
                'description': friendly_msg,
                'source': 'error'
            }
    
    def _get_placeholder_response(self, message):
        """
        Generate placeholder responses when API is not available.
        """
        message_lower = message.lower()
        
        # Simple keyword-based responses
        responses = {
            'hello': "Hello! I'm your AI assistant. How can I help you today?",
            'hi': "Hi there! I'm here to assist you. What would you like to know?",
            'help': "I'm an AI assistant powered by Google Gemini. You can ask me questions about anything, and I'll do my best to help you.",
            'what': "That's an interesting question! With the Gemini API configured, I can provide detailed answers.",
            'how': "I can explain that! Once the API is set up, I'll give you comprehensive information.",
            'who': "Let me tell you about that. With AI capabilities, I can provide accurate information.",
            'braille': "Braille is a tactile writing system used by people who are visually impaired. It consists of patterns of raised dots arranged in cells.",
            'book': "I can help you find and read books! What genre or topic interests you?",
            'news': "I can provide news summaries. What category of news would you like to hear about?",
            'time': "I can help with time-related queries once fully configured.",
            'weather': "I can provide weather information with the right API access.",
        }
        
        # Find matching keyword
        for keyword, response in responses.items():
            if keyword in message_lower:
                return {
                    'status': 'success',
                    'response': response,
                    'source': 'placeholder'
                }
        
        # Default response
        return {
            'status': 'success',
            'response': f"I heard you say: '{message}'. This is a placeholder response. With Google Gemini API configured, I can provide intelligent answers to your questions.",
            'source': 'placeholder'
        }


# Singleton instance
_gemini_service = None

def get_gemini_service():
    """
    Get singleton instance of GeminiService.
    
    Returns:
        GeminiService: Singleton instance
    """
    global _gemini_service
    if _gemini_service is None:
        _gemini_service = GeminiService()
    return _gemini_service
